heat_template_version: 2013-05-23

description: Demo template to wait condition

resources:
  test_instance:
    type: OS::Nova::Server
    properties:
      image: centoswithroot
      flavor: m1.small
      key_name: ashwa
      networks:
        - network: int-net
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            echo "+Info: Test the instance with wait"
            onexit
            function onexit() {
               curl -X PUT -H 'Content-Type:application/json' -d '{"Status" : "SUCCESS","Reason" : "Configuration Passed","UniqueId" : "console","Data" : "CONSOLE Configured."}' '$wait_handle'
             }
          params:
            $wait_handle: { get_resource: wchandle }
  waitcondition:
    type: AWS::CloudFormation::WaitCondition
    depends_on: test_instance
    properties:
      Count: 1
      Handle: {get_resource: wchandle}
      Timeout: 300

  wchandle:
    type: AWS::CloudFormation::WaitConditionHandle
